<a href="https://colab.research.google.com/github/ayushm1998/CODING/blob/master/mathops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy

In [4]:
a=np.array([2,7,1,99,4])
type(a)

NameError: ignored

In [0]:
import numpy as np

In [6]:
a=np.array([2,7,1,99,4])
type(a)


numpy.ndarray

In [7]:
a

array([ 2,  7,  1, 99,  4])

In [8]:
a[0]

2

In [9]:
b=np.array([12,17,11,99,14])
type(b)

numpy.ndarray

In [10]:
b[0]


12

In [11]:
a[1]+b[3]

106

In [12]:
a*2

array([  4,  14,   2, 198,   8])

In [13]:
a**2

array([   4,   49,    1, 9801,   16])